POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "testName",
  "username": "testUsername",
  "password": "123456",
  "email": "email@email.com"
}

###

GET http://localhost:3000/users/676de40a3612bfbde406d471