POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "testName",
  "username": "usernameTest",
  "email": "email"
}

###

GET http://localhost:3000/users/676de40a3612bfbde406d471